feat: enabled chart tab for button object along with maintaining backward compatibility of properties
qlik-oss/sn-action-button pull request #339
Opened 2022-12-22 11:38 UTC by rajani-varpe

This PR intends to enable the chart tab in button object along with backward compatibility of editor properties except the background Image using Media Library.

Background Image using Media Library is working fine in Styling Panel, the action item to get this working with backward compatibility is to add the correct condition in MediaLibrary component. This functionality works fine with "**args.properties**" (MediaLibrary Component)but later this has been changed to "**args.handler.layout.component**" which tend to fail as we do not have any "components" in style editor. 

So this condition needs to be handled to get this working properly.

### 1. Styling Panel

<img width="771" alt="image" src="https://user-images.githubusercontent.com/103170180/209126071-74a80856-dc05-495a-bb73-d5131899fc59.png">

### 2. Style Editor - without FF

<img width="416" alt="image" src="https://user-images.githubusercontent.com/103170180/209125298-eabf3a3f-4688-47b1-84d2-43af569a685c.png">

### 3. Styling Panel - with FF

<img width="765" alt="image" src="https://user-images.githubusercontent.com/103170180/209125794-8e04586f-1f9f-4078-847c-6f38ca0f9c63.png">

2023-01-12 14:42 UTC, Donya-qlik commented
@AmeliaAndersson @LiKang6688 @niekvanstaveren Could you please start reviewing this PR? I'll take care of this PR since the responsible person is not working with Qlik anymore. Thanks!

**Note**: Rajani has mentioned in his explanations that Media Library is not working with `args.layout.properties`. I'm not sure I understood what he meant. Media Library works properly in sense-client as an extension as far as I tested it. Let me know if you have any idea about it. Thanks.

2023-01-23 10:42 UTC, niekvanstaveren requested changes
A couple things here really need to be fixed. I would actually suggest starting a new PR for this.

Have not tested things myself, but I am pretty sure that there will be some issues when using the new options. For instance what would happen if I have a background selected in the old setup and now want to change the font color with the feature flag active. Do I still get the old background settings applied?

2023-01-23 10:42 UTC, niekvanstaveren commented on src/styling-panel-definition.js
> +            console.log("show=>labelSection=>", args)
Remove all console.log statements before merging

2023-01-23 10:42 UTC, niekvanstaveren commented on src/styling-panel-definition.js
> +          translation: 'Label',
Is this a real translation?

2023-01-23 10:42 UTC, niekvanstaveren commented on src/styling-panel-definition.js
> +          show(data, handler, args) {
What is this show function supposed to do? It just return true in the end, but there is a lot of logic in here which should not be here

2023-01-23 10:42 UTC, niekvanstaveren commented on src/styling-panel-definition.js
> +              key: 'actionbutton',
I don't think these need to be in the components array. Only when this is something that could be generic it should be placed in components. The key `actionbutton` already shows that it is probably not generic

2023-01-23 10:42 UTC, niekvanstaveren commented on src/styling-panel-definition.js
> +        bgColorSection: {
Why do we have this now both in the general tab and the chart tab?

2023-03-28 10:24 UTC, closed without merging